"""add_pgvector_and_chunk_embedding

Revision ID: 17fc5970a5cf
Revises: 3df3ef891c58
Create Date: 2026-09-01 22:04:46.867373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '17fc5970a5cf'
down_revision: Union[str, None] = '3df3ef891c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable PostgreSQL pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Add columns
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    op.add_column('chunks', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding_model')
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
