"""add_active_version_to_documents

Revision ID: 23be02d517bf
Revises: 9c19f8694ab0
Create Date: 2026-09-01 22:51:41.578304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23be02d517bf'
down_revision: Union[str, None] = '9c19f8694ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('active_version_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_active_version_id'), 'documents', ['active_version_id'], unique=False)
    op.create_foreign_key('fk_documents_active_version_id', 'documents', 'document_versions', ['active_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_active_version_id', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_active_version_id'), table_name='documents')
    op.drop_column('documents', 'active_version_id')
    # ### end Alembic commands ###
