"""add_enterprise_metadata_to_documents

Revision ID: a1d4e22ac020
Revises: 23be02d517bf
Create Date: 2026-09-01 23:06:45.481099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1d4e22ac020'
down_revision: Union[str, None] = '23be02d517bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('documents', sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_documents_department'), 'documents', ['department'], unique=False)
    op.create_index(op.f('ix_documents_effective_date'), 'documents', ['effective_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_effective_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_department'), table_name='documents')
    op.drop_column('documents', 'extra_metadata')
    op.drop_column('documents', 'effective_date')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'department')
    # ### end Alembic commands ###
